### ISSUE TITLE
create MET files from local NetCDF files

### ISSUE THREAD

**Issue by JJguri** [JJguri/bestiapop#10]
this functionality is needed to create network independency. So, people able to download NetCDF files locally can create MET files without an internet connection

**Comment by darkquasar** [comment]
added ability to read local NetCDF files in commit [b193843](https://github.com/JJguri/bestiapop/commit/b193843). 

**ToDo**
1. Please check and confirm it's working

**Comment by JJguri** [comment]
It is working well. Generating the MET files from a local NetCDF file increase considerably the efficiency (1.15 min/file of 30 years each).

**Comment by darkquasar** [comment]
Awesome then I'm closing this issue.
