### ISSUE TITLE
Implement MultiProcessing to allow for the parallelization of workloads

### ISSUE THREAD

**Issue by JJguri** [JJguri/bestiapop#11]
it will improve the efficiency to download long-term data and large amounts of files.

**Comment by darkquasar** [comment]
Multiprocessing has been implemented for **BestiaPop v2.5** (commit 0a7e63f) for the main operation that generates MET files (either from the cloud or local files). The data extraction and output generation have both been parallelized. This will be extended to other functionalities as the project continues to develop.

Documentation has been updated as well.
