### ISSUE TITLE
time counter is showing zero values for long jobs

### ISSUE THREAD

**Issue by JJguri** [JJguri/bestiapop#12]
I downloaded more than 400 files (1960-1990) together and it took more than 20 hs or a day approx (could be more than 24 hs). When the job finished the time counter only shows values for the minute and sec fields. The field hour was zero.

**Comment by darkquasar** [comment]
fixed in **BestiaPop v2.5** commit 0a7e63f, basically we just needed to include the counter for `days` in the output, since total elapsed hours and minutes is calculated based on a *quotient and remainder* operation using `divmod`:

```python
  days = (et-st).days
  hours, remainder = divmod((et-st).seconds, 3600)
  minutes, seconds = divmod(remainder, 60)

  logger.info("Finished this unit of work")
  logger.info('Workload took: \x1b[47m \x1b[32m{} days / {} hours / {} minutes / {} seconds \x1b[0m \x1b[39m'.format(days,hours,minutes,seconds))
```
