### ISSUE TITLE
Logo for bestiapop

### ISSUE THREAD

**Issue by JJguri** [JJguri/bestiapop#17]
First attempt to create a logo. What do you think? @darkquasar 
![logov1](https://user-images.githubusercontent.com/41041705/86503058-85ecaa00-bded-11ea-9b39-a93ed062fa00.png)

**Comment by darkquasar** [comment]
love it! let's make it official

**Comment by darkquasar** [comment]
added to readthedocs page, check it out and if you like it we can close this issue

**Comment by JJguri** [comment]
all good, just close it.
