### ISSUE TITLE
differences in number of decimals for amp

### ISSUE THREAD

**Issue by JJguri** [JJguri/bestiapop#2]
For some reason, in some files (only some of them) the amp values have more than 5 decimals (only for amp, not for tav).

**Comment by darkquasar** [comment]
This might be due to a commit breaking the explicit decimal round ups:

![image](https://user-images.githubusercontent.com/28435534/80955671-ff463b80-8e42-11ea-8b4d-ad4584e9684b.png)

I've fixed that now implementing *numpy's round() function*

**Comment by darkquasar** [comment]
fixed in commit [177ae4a](https://github.com/JJguri/bestiapop/commit/177ae4a)
