### ISSUE TITLE
ability to create WTH files for DSSAT

### ISSUE THREAD

**Issue by JJguri** [JJguri/bestiapop#20]
*bestipop* should be able to create weather files for other models than APSIM (e.g. in a DSSAT format).

DSSAT Weather Files are simple files that have an extension .WTH (analogous as .MET in APSIM). The minimum required weather data include:

Latitude and longitude of the weather station,
Daily values of incoming solar radiation (MJ/m²-day),
Maximum and minimum daily air temperature (ºC), and
Daily total rainfall (mm).

[example](https://www.dropbox.com/s/e0nq7jrf83tmu76/DIJY8601.WTH?dl=0)

Points to be considered:
* Row 1, should be the combined name from lat-lon (e.g -39.7-144.1) as in MET files.
* Row 3 and 4, lat and long are mandatory, then if data is not available it should be -99.0. TAV and AMP are the same parameters as in MET files.
* Row 5, Mandatory variables are SRAD, TMAX, TMIN, and RAIN. Others can be deleted including heads.
* First column, it is the concatenation of year '1986' and Julian day '001', e.g. Row 6 is 86001.

**Comment by darkquasar** [comment]
So the latest commit to the *dev* branch contains the ability to generate *DSSAT* files. It's 90% done but I need to ask you some things. Output at the moment looks like this:

```
*STATION NUMBER : -41.0-145.65
*WEATHER DATA : BestiaPop
*DATA SOURCE : SILO

@ INSI    LAT   LONG  ELEV TAV  AMP  REFHT WNDHT
    DIJY   -41.0 -145.65 -99.0 12.6 10.1 -99.0 -99.0
@DATE  SRAD  TMAX  TMIN  RAIN
10001 30.3 27.7 13.8 0.3
10002 27.1 19.8 11.9 0.0
10003 25.0 19.2 9.0 0.0
10004 24.5 20.8 8.9 0.0
10005 22.2 23.2 11.7 0.0
10006 29.6 21.7 11.3 0.0
10007 31.9 20.6 4.3 0.0
...
10360 24.0 17.7 10.1 0.0
10361 27.8 15.7 4.2 1.3
10362 17.9 16.8 4.4 0.2
10363 23.0 21.0 7.5 0.0
10364 28.6 21.2 6.1 0.0
10365 19.0 18.7 6.7 0.0
```

What I would like to know is:
1. Is the asterisk sign the symbol used for "comments"?
2. Are the comments added at the beginning ok or should they be trimmed down to what you mentioned earlier? What should I get rid of?
3. As you can see, the values for SRAD  TMAX  TMIN  RAIN are _not_ aligned with their headers, I would imagine this is not an issue for the software that reads DSSAT files, but I would like to know whether it is fine to leave it like that or not
4. The LAT and LONG values for the DSSAT file you provided as example have tree decimals after the dot, is this important?
5. Anything else?

**Comment by darkquasar** [comment]
fixed alignment issues with DSSAT output file in dev, *note:* _it is slower to create DSSAT files since BestiaPop needs to do a lot of ASCII operations to get the alignment right_. Having said this, it is properly aligned *to the right*, as per DSSAT requirements, so it should be readable.

**Comment by JJguri** [comment]
Answers to your questions:
1- I checked in several sources an all have only one row with the asterisk indicating the name of the location, the lat-lon combination is fine.
2- just keep a single row as I mentioned before.
3- needs to be aligned, it's done
4- Considering our current source data which provides climate data with a frequency of 0.05 degree, two decimals would be fine, however, if we include other sources with data at <0.01 degree a third decimal would be needed. So keep three.  
5- Please maintain one decimal in all variables, e.g. for days without rain should be 0.0.
6- the four digits below @INSI indicate the name of the location which, I think, then is used to create treatments in DSSAT. In the example, I provided the place was in Jyndevad, Denmark somewhere (DIJY). This is limited to 4 digits so we need to find a way to create a name from the lat-lon only with 4 digits, e.g. for -41.15-145.5 could be 4145 (which is quite approx to that grid). Anyways the name is above in the first row.
7-The name of the WHT file need to be created by convention in a DSSAT format. Please check page 9 [here](http://www.ukm.my/seaclid-cordex/files/Rice%20Pilot%20Project%20Workshop/PRESENTATION-PDF/20140922-1430-1445-Weather%20data%20format%20of%20%20DSSAT%20model--%20Attachai.pdf). Instead to put 4 digits for the place please put more digits which are the combination between lat and lon -41151455 and then the initial year and the amount of years in the file. For this example, the final name should be -411514551501.WHT. Note that if NASAPOWER is included as source data we will have negative longitudes, so this name could have an extra digit before the longitude, so could be 13 or 14 digits.

**Comment by JJguri** [comment]
@darkquasar please consider the following head format (with the specific decimals described below) for the updated WTH files.
![Untitled](https://user-images.githubusercontent.com/41041705/91515486-a5efa400-e92c-11ea-91eb-cf8285898a43.jpg)
