### ISSUE TITLE
improvement in the header of a climate file

### ISSUE THREAD

**Issue by JJguri** [JJguri/bestiapop#21]
We should include additional information in the head of each output file created by *bestiapop*. It just needs to be preceded by the symbol '!', so the model will not read this info. I suggest to add the following information after !station number:

!This climate file is created by bestiapop on 'add date' 
!Source: SILO or NASAPOWER (depending on the choice of the user)
!Date period from 'year'+'JulianDay' to 'year'+'JulianDay'

**Comment by darkquasar** [comment]
This should be easy to do, I will look into it for version 2.7 currently in dev branch

**Comment by darkquasar** [comment]
so what do you mean by `year+JulianDay` usually you only pass the year range to the script, so it would look something like:

```
!Date period from 2015 to 2018
```

is this what you are after?

**Comment by JJguri** [comment]
Yes, you are right and the statement you provided is correct. I just provided an example for the DSSAT format. In some cases (not using bestiapop) weather files do not start from the Julian day 1 and do not finish in the 365. Please see the example I provided for a DSSAT file, it was taken from somewhere. For the MET and WHT files cerated with bestiapop the period always will be from Julian day 1 until the end of the year, so you should provide the period of years `!Date period from 2015 to 2018` only and in the case of one year just !Date period from year1 to year1.

**Comment by JJguri** [comment]
@darkquasar Please have a look at the headers for MET files. I am providing some suggestions:

[weather.met.weather] :heavy_check_mark:
!station number=-41.15-145.5   _Could be negative if data is from the east hemisphere, is bestiapop prepared for that?_
!This climate file is created by BestiaPop on   _Please add date in ddmmyyy format and the link to bestiapop documentation after the word Bestiapop_ 
!Source: SILO   _Please write SILO (Scientific Information for Land Owners) (https://www.longpaddock.qld.gov.au/silo/). If the data is downloaded from the NASAPOWER source add the link to NASAPOWER_
!Date period from:  to   _Please complete start and end year. If it is a single year write from 2015 to 2015_
Latitude=-41.15   :heavy_check_mark:
Longitude=145.5   :heavy_check_mark:
tav=10.41699   _Please only two digits_
amp=10.16152   _Please only two digits_
