### ISSUE TITLE
Running with `-a download-and-convert-to-met` doesn't work

### ISSUE THREAD

**Issue by hol430** [JJguri/bestiapop#22]
Hi @jjguri, just found a minor oversight in the help info generated by running with the `-h` flag. It says that there's an option to download and convert to met format in one go with `-a download-and-convert-to-met`:

```
  -a {download-silo-file,convert-nc4-to-met,convert-nc4-to-csv,generate-met-file}, --action {download-silo-file,convert-nc4-to-met,convert-nc4-to-csv,generate-met-file}
                        The type of operation to want to perform: download-silo-file (it will only download a particular SILO file from S3 to your
                        local disk), convert-nc4-to-met (it will only convert a local or S3 file from NC4 format to MET), convert-nc4-to-csv(it will
                        only convert a local or S3 file from NC4 format to CSV), download-and-convert-to-met (combines the first two actions)
```

However if I try to use this option, I get the following error:

```sh
bestiapop.py: error: argument -a/--action: invalid choice: 'download-and-convert-to-met' (choose from 'download-silo-file', 'convert-nc4-to-met', 'convert-nc4-to-csv', 'generate-met-file')
```

**Comment by darkquasar** [comment]
Hi @hol430 indeed that is a missing option at the moment, however, I believe it should be an actual option because some users might actually want to be able to download a NetCDF4 file to disk and then generate a MET file out of it. I will flag this as an enhancement for version 2.7 and I will remove the misleading info from the help.

**Comment by darkquasar** [comment]
Hi @hol430, we've decided to drop this feature since the same functionality can be achieved by combining the two actions `download-nc4-file` and `generate-climate-file` (of course run in different instances, first downloading, then generating the output).
