### ISSUE TITLE
SILO Gridded data consistency issue - Netcdf vs API

### ISSUE THREAD

**Issue by JJguri** [JJguri/bestiapop#28]
There are particular years where some data can be different using Netcdf or SILO API. Below is a detailed description of the SILO team. @darkquasar please check what information we should include in the documentation to alert users about this inconsistency.

When you request point data at grid cell locations, the data are:
1.	extracted from the relevant grid cell in the NetCDF files
2.	passed through a simple filter that checks if each datum is within an acceptable range:
•	daily rainfall: 0 – 1300 mm
•	maximum temperature: -9 - 54 ᵒC
•	minimum temperature: -20 - 40 ᵒC
•	class A pan evaporation: 0 - 35 mm
•	solar radiation: 0 - 35 MJ/m2
•	vapour pressure: 0 - 43.2 hPa
•	maximum temperature > minimum temperature
If a given datum (or pair of data values for the Tmax > Tmin check) fails the check, it/they may be erroneous so SILO provides the long term daily mean(s) instead.

If you request data at station locations the same checks are done; the main difference is observed data are provided where possible, and gridded data are provided if observed data are not available on a given day(s).

We have checked the maximum temperature examples you provided. Differences between the API and NetCDF values only occur when a datum fails one of the aforementioned range checks, or in this particular case, when the interpolated maximum temperature is lower than the interpolated minimum temperature. Such situations typically arise due to errors in the observed data (leading to errors in the gridded surface), or in regions where there are very few recording stations. We expect there to be more errors in the gridded surfaces for the early years, as there were relatively few stations recording data (other than rainfall) before 1957. Plots showing the number of stations recording each variable as a function of time are provided in our 2001 paper (see the Publications section on our web page).

As noted above, when errors are detected the suspect data are replaced by the long term daily mean. You can easily identify the replacements by the source code which is provided in many of our data formats. For example, if you use the API to request data in “standard” format for location 41.15 ᵒS, 145.50ᵒE you will obtain:

Date       Day T.Max Smx T.Min Smn Rain   Srn  Evap Sev Radn   Ssl VP    Svp RHmaxT RHminT Date2
(yyyymmdd)  ()  (oC)  ()  (oC)  ()   (mm)  ()  (mm)  () (MJ/m2) () (hPa)  ()   (%)    (%)  (ddmmyyyy)
19450306    65  11.8  35   7.5  35    5.2  25   3.3  75  15.9   35  10.8  35   78.1  100.0  6/03/1945
19450307    66  15.8  35   7.9  35    0.9  25   3.3  75  13.2   35  10.5  35   58.5   98.6  7/03/1945
_19450308    67  18.2  **75**   9.2  **75**    6.0  25   3.2  75  18.6   35   9.4  35   45.0   80.8  8/03/1945_
19450309    68   9.4  35   5.6  35    5.9  25   3.0  75  16.6   35  10.0  35   84.8  100.0  9/03/1945
19450310    69  10.2  35   7.5  35    1.9  25   2.9  75  15.9   35   9.0  35   72.4   86.9 10/03/1945

The source codes are provided in the header section (not shown above). Code 75 means the datum is a long term daily mean. As shown in the data extract above, the Tmax and Tmin data provided for 9 March 1945 are long term daily means (not interpolated daily values) because the interpolated values failed the Tmax > Tmin check. As shown in your spreadsheet, the interpolated Tmax is 8.7 ᵒC (cell K20524) and the interpolated Tmin is 8.8 ᵒC (cell L20524) for that particular day and location.

**Comment by darkquasar** [comment]
This has been added to the documentation under the "SILO" section as per commit c500e50. Please let me know if it's clear enough.

Added:

```
About SILO
==========

SILO is a database of Australian climate data from 1889 to the present. It provides daily meteorological datasets for a range of climate variables in ready-to-use formats suitable for biophysical modelling, research and climate applications.

NetCDF and API data variations from SILO
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

There are particular years where some data may be different when you read the data from a `NetCDF SILO file`, as opposed to reading the same data from the `SILO API`. Below is a detailed description of the SILO team as to why this might happen.

When you request point data at grid cell locations, the data is extracted from the relevant grid cell in the NetCDF files. This data is then passed through a simple filter that checks if each datum is within an acceptable range:

  * daily rainfall: 0 – 1300 mm
  * maximum temperature: -9 - 54 ᵒC
  * minimum temperature: -20 - 40 ᵒC
  * class A pan evaporation: 0 - 35 mm
  * solar radiation: 0 - 35 MJ/m2
  * vapour pressure: 0 - 43.2 hPa
  * maximum temperature > minimum temperature

If a given datum (or pair of data values for the Tmax > Tmin check) fails the check, it/they may be erroneous so SILO provides the long term daily mean(s) instead. This is represented by a number *75* in the value for a particular datum.

If you request data at station locations the same checks are done; the main difference is observed data are provided where possible, and gridded data are provided if observed data are not available on a given day(s).

> Differences between the API and NetCDF values only occur when a datum fails one of the aforementioned range checks, for example, when the interpolated maximum temperature is lower than the interpolated minimum temperature. Such situations typically arise due to errors in the observed data (leading to errors in the gridded surface), or in regions where there are very few recording stations. We expect there to be more errors in the gridded surfaces for the early years, as there were relatively few stations recording data (other than rainfall) before 1957. Plots showing the number of stations recording each variable as a function of time are provided in our 2001 paper (see the [Publications section on SILO](https://www.longpaddock.qld.gov.au/silo/about/publications-references/)).
```

**Comment by JJguri** [comment]
all good with this
