### ISSUE TITLE
package installation in binder

### ISSUE THREAD

**Issue by JJguri** [JJguri/bestiapop#35]
@darkquasar could you please include these packages in binder? I would like to plot the data and create maps and features. To do this it is mandatory to work directly in binder or I can develop the code in the BestiaPop file in the sample folder?? I am thinking if binder is reading directly that file hosted in Git.

```
import random as rd
import os
import sqlite3
import datetime
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap
from matplotlib import colors
import matplotlib.ticker as ticker
from mpl_toolkits.axes_grid.inset_locator import (inset_axes, InsetPosition,mark_inset)
import dateutil
import pylab as py
import seaborn as sns
import scipy 
from scipy import stats
import sklearn.metrics
from numpy  import array
import functools
from functools import reduce
import xarray as xr
import cartopy.crs as ccrs
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
import cartopy.feature as cfeature
import cartopy.io.shapereader as shpreader
from sklearn.cluster import KMeans
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
from netCDF4 import Dataset
import xarray as xr
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
import glob
import geopandas as gpd
```

**Comment by darkquasar** [comment]
Done!, MyBinder environment updated you can now import all these packages. If there are other packages that you can't import, just add them to file [environment.yml](https://github.com/JJguri/bestiapop/blob/master/environment.yml). If they can be installed by anaconda, then add them in the upper part of the file. If they can only be installed with `pip`, then add them under the `pip` section.
