### ISSUE TITLE
error to download files from nasapower

### ISSUE THREAD

**Issue by JJguri** [JJguri/bestiapop#41]
@darkquasar I was using bestiapop to download met files from silo and nasapower a couple of months ago and it was working. Now it is only working for silo. When I changed the source to nasapower, it produce the following error:
![image](https://user-images.githubusercontent.com/41041705/146624994-7d4cd1c9-210c-40da-a7c2-9189dd65407d.png)
I reproduce the error in command line and Binder and it is the same. Maybe a change was made in the way nasapower storage the data in the netcdf? Seems to be an issue with the attribute `features` in the json files. I would appreciate if you can help me with this. Thanks

**Comment by darkquasar** [comment]
Hi @JJguri how are you, I'm not maintaining this project anymore mate, but I'm pretty sure this has to do with a change in the JSON structure of the data returned by NasaPower API. So if you can make a call to NasaPower API and see what the new structure is, you should be able to go to that line 201 in the error and adapt the python dict to reflect the new structure. I would recommend [postman](https://www.postman.com/downloads/) it's really good for testing APIs. 

It looks like one of those things that should be relatively easy to fix but as we know, nothing is easy to fix!

Best of luck with the project

**Comment by JJguri** [comment]
@darkquasar thanks for the reply. I found that NASAPOWER has recently changed the API and the JSON structure as was expected. I have updated bestiapop and it is working well again. Thanks
