### ISSUE TITLE
Transfer of Pypi ownership to jjguri

### ISSUE THREAD

**Issue by darkquasar** [JJguri/bestiapop#42]
Hi @JJguri, **I would like to transfer the ownership of the BestiaPop package in Pypi to you**, so that you can continue publishing updated versions of the package there. Can you please create yourself an account in https://pypi.org? Once you've done that, _I will add you to the package as an Owner_ and I will remove myself, you will then have complete control over the Pypi package :)

**Comment by JJguri** [comment]
@darkquasar thanks for this. I have created and account in Pypi. My username is **JJguri** please feel free to proceed with the plan. Thanks

**Comment by darkquasar** [comment]
Cool it's done, you should receive an invite, once you confirm that I will remove myself from the project, thanks.

**Comment by darkquasar** [comment]
I can see you have been added as owner now, I cannot remove myself from the Pypi project but at least you can publish new packages now if required. Feel free to remove me if needed. Thanks
