### ISSUE TITLE
number of output files in not an entire factorial between lat and lon

### ISSUE THREAD

**Issue by JJguri** [JJguri/bestiapop#5]
We are creating the wrong number of output files, so the code is not producing an entire factorial with latitudes and longitudes. For example, for the following combination -lat "-41.2 -41.25" -lon "146.3 146.35", the code is just creating 1 file (-41.25-146.3), i.e. it is just considering the second latitude and the first longitude.

**Comment by darkquasar** [comment]
numpy.arange has an erratic behaviour with floats: https://numpy.org/doc/stable/reference/generated/numpy.arange.html. 

In the docos they state *When using a non-integer step, such as 0.1, the results will often not be consistent. It is better to use numpy.linspace for these cases.*

Applied fix to account for missing values in commit d7e0d8e
