### ISSUE TITLE
Improve Readme landing section

### ISSUE THREAD

**Issue by darkquasar** [JJguri/bestiapop#6]
The readme.md landing file needs to be improved explaining what a MET file is, what is APSIM, and adding links to the other model formats DSSAT and STICS.

**Comment by JJguri** [comment]
check if everything is fine, otherwise close the issue

**Comment by darkquasar** [comment]
looks good to me, proper documentation will be hosted in readthedocs.io so we might have to migrate some stuff there too.

**Comment by JJguri** [comment]
I think we should add future developments also.
